### ISSUE TITLE
Failure of 'Export all text as POS list'

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/gramlab-ide#77]
The Table pane of the 'FST-text' window contains an 'Export all text as POS list' button that converts the text automaton into a 'POS list' format. This function fails on some corpora.

**What steps will reproduce the problem?**

Open the attached Korean text and click the  'Export all text as POS list' button.
[1-Creative writing-NF-25000_snt.zip](https://github.com/UnitexGramLab/gramlab-ide/files/830823/1-Creative.writing-NF-25000_snt.zip)

**What is the expected output?**

The progress bar reaches the right end.

**What do you see instead?**

The progress bar stops.

**Comment by vince21298** [comment]
Hi. I am new to the open source community and will be my first contribution. I want to take a crack at the problem. Thank you.

**Comment by martinec** [comment]
Hi @vince21298, I labelled the issue as `status:in-progress` since you mentioned you wanted to work on it.

**Comment by vince21298** [comment]
Sorry, something came up and I need to push it to a later time. I want to
let other people take a crack at it.

On Sat, Aug 12, 2017 at 7:16 AM, Cristian Martinez <notifications@github.com

**Comment by martinec** [comment]
There is no problem @vince21298, you can come back anytime and explore other issues with the label [`first-timers-only`](http://goo.gl/zfIsQZ).

**Comment by madcated** [comment]
Hello, I tested with the example file and 'Export all text as POS list' action could be finished normally. The version is Rev. 4314. It seems this issue has been solved, right?

**Comment by eric-laporte** [comment]
Hi madcated,
I tested with the example file, running Unitex version 3.2alpha Rev. 56 under Windows 10, and 'Export all text as POS list' stops very soon (about sentence 35) with the following error message:
"Error in file C:(...)\Korean\Corpus\1-Creative writing-NF-25000_snt\foo.grf: Number expected"
So the issue is still pending.
In case it helps, the same experiment with [2-Creative writing-NF-25000_snt.zip](https://github.com/UnitexGramLab/gramlab-ide/files/1356503/2-Creative.writing-NF-25000_snt.zip) does complete normally (both with version 3.1 Rev 4314 and with version 3.2alpha Rev. 56).
